/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_aoit_hmcrfidwriter_lib_jni_RFIDComponent */

#ifndef _Included_ru_aoit_hmcrfidwriter_lib_jni_RFIDComponent
#define _Included_ru_aoit_hmcrfidwriter_lib_jni_RFIDComponent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_aoit_hmcrfidwriter_lib_jni_RFIDComponent
 * Method:    receiveMessage
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_ru_aoit_hmcrfidwriter_lib_jni_RFIDComponent_receiveMessage
  (JNIEnv *, jclass);

/*
 * Class:     ru_aoit_hmcrfidwriter_lib_jni_RFIDComponent
 * Method:    sendMessage
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_ru_aoit_hmcrfidwriter_lib_jni_RFIDComponent_sendMessage
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     ru_aoit_hmcrfidwriter_lib_jni_RFIDComponent
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_aoit_hmcrfidwriter_lib_jni_RFIDComponent_start
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
